// AUTO-GENERATED by scripts/build-world.ts. Do not edit.
// SPEC Section 19.2 asset hashing contract. Phase 1a MVP: plain paths; content hash deferred.

export interface AssetManifest {
  worldJson: string;
  polygonsTier1: string;
  polygonsTier2: string;
  bordersTier1: string;
  bordersTier2: string;
  adjacencyJson: string;
}

export const manifest: AssetManifest = {
  worldJson: '/geo/world.json',
  polygonsTier1: '/geo/world.polygons.tier1.json',
  polygonsTier2: '/geo/world.polygons.tier2.json',
  bordersTier1: '/geo/world.borders.tier1.json',
  bordersTier2: '/geo/world.borders.tier2.json',
  adjacencyJson: '/geo/adjacency.json',
};
