/**
 * Manifest loader. SPEC v1.0 Section 4.3 + 7.1.
 *
 * Fetches /data/manifest.json (auto-generated by bake script). Returns
 * tier filename + content-hash mapping for runtime fetch.
 */

export interface TierManifestEntry {
  file: string;             // e.g. "tiles/world-50km.{hash}.bin.gz"
  sizeKm: number;
  hexCount: number;
  bytesCompressed: number;
  hash: string;
}

export interface Manifest {
  schemaVersion: 1;
  tiles: Record<string, TierManifestEntry>;
}

let cached: Manifest | null = null;

export async function loadManifest(): Promise<Manifest> {
  if (cached) return cached;
  const res = await fetch('/data/manifest.json', { credentials: 'omit' });
  if (!res.ok) throw new Error(`manifest fetch ${res.status}`);
  const m = (await res.json()) as Manifest;
  if (m.schemaVersion !== 1) {
    throw new Error(`manifest schemaVersion=${m.schemaVersion} not supported`);
  }
  cached = m;
  return m;
}
